### ISSUE TITLE
[feat] STEP 1

### ISSUE THREAD

**Issue by jane1choi** [jane1choi/ios-rock-scissor-paper#1]
## 🤚🏻 Feature Issue
- STEP 1의 기능을 구현합니다.

## 📝 To-do
- [x] 최초 실행 시 사용자에게 출력문 보여주기
- [x] 가위바위보 진행
    - [x] 컴퓨터는 임의의 패 내기
    - [x] 사용자 입력 받기(0, 1, 2, 3, 나머지 에러 처리)
        - [x] 0: 게임 종료
        - [x] 1~3: 게임 결과에 따른 분기처리(비긴 경우, 이긴 경우, 진 경우)
            - [x] 비긴 경우: 출력 후 최초 실행 상태로 복귀
            - [x] 이긴 경우: 출력 후 프로그램 종료
            - [x] 진 경우: 출력 후 프로그램 종료
        - [x] 이외의 값: 에러문 출력 후 최초 실행 상태로 복귀
