### ISSUE TITLE
[feat] STEP 2

### ISSUE THREAD

**Issue by Nnn-Park** [jane1choi/ios-rock-scissor-paper#2]
## 🤚🏻 Feature Issue
- STEP 2 묵찌빠 프로그램을 만듭니다.

## 📝 To-do
- [x] 가위, 바위, 보 게임을 이긴 후 묵찌빠게임으로 넘어가는 기능 구현
- [x] 묵, 찌, 빠 실행 시 기본 메세지 출력
- [x] 턴 기능 구현
    - [x] 잘못된 입력을 한 경우 컴퓨터에게 턴을 넘기는 기능 구현
- [x] 턴을 쥔 상태에서 다음 패가 동일 할 시 턴을 쥐고 있는 쪽이 승리
    - [x]  턴을 쥔 상태에서 다음 패가 다를 시, 승리한 쪽이 턴을 쥐는 기능 구현
- [x] 0을 입력 받을 경우 게임 종료 메세지 출력
